export const AVATARS = {
  "1": require('../../assets/avatars/avatar_1.png'),
  "2": require('../../assets/avatars/avatar_2.png'),
  "3": require('../../assets/avatars/avatar_3.png'),
  "4": require('../../assets/avatars/avatar_4.png'),
  "5": require('../../assets/avatars/avatar_5.png'),
  "6": require('../../assets/avatars/avatar_6.png'),
  "7": require('../../assets/avatars/avatar_7.png'),
  "8": require('../../assets/avatars/avatar_8.png'),
  "9": require('../../assets/avatars/avatar_9.png'),
  "10": require('../../assets/avatars/avatar_10.png'),
  "11": require('../../assets/avatars/avatar_11.png'),
  "12": require('../../assets/avatars/avatar_12.png'),
  "13": require('../../assets/avatars/avatar_13.png'),
  "14": require('../../assets/avatars/avatar_14.png'),
  "15": require('../../assets/avatars/avatar_15.png'),
  "16": require('../../assets/avatars/avatar_16.png'),
  "17": require('../../assets/avatars/avatar_17.png'),
  "18": require('../../assets/avatars/avatar_18.png'),
  "19": require('../../assets/avatars/avatar_19.png'),
  "20": require('../../assets/avatars/avatar_20.png'),
  "21": require('../../assets/avatars/avatar_21.png'),
  "22": require('../../assets/avatars/avatar_22.png'),
  "23": require('../../assets/avatars/avatar_23.png'),
  "24": require('../../assets/avatars/avatar_24.png'),
  "25": require('../../assets/avatars/avatar_25.png'),
  "26": require('../../assets/avatars/avatar_26.png'),
  "27": require('../../assets/avatars/avatar_27.png'),
  "28": require('../../assets/avatars/avatar_28.png'),
  "29": require('../../assets/avatars/avatar_29.png'),
  "30": require('../../assets/avatars/avatar_30.png'),
  "31": require('../../assets/avatars/avatar_31.png'),
  "32": require('../../assets/avatars/avatar_32.png'),
  "33": require('../../assets/avatars/avatar_33.png'),
  "34": require('../../assets/avatars/avatar_34.png'),
  "35": require('../../assets/avatars/avatar_35.png'),
  "36": require('../../assets/avatars/avatar_36.png'),
  "37": require('../../assets/avatars/avatar_37.png'),
  "38": require('../../assets/avatars/avatar_38.png'),
  "39": require('../../assets/avatars/avatar_39.png'),
  "40": require('../../assets/avatars/avatar_40.png'),
  "41": require('../../assets/avatars/avatar_41.png'),
  // Admin-only — stored in AVATARS so AVATARS[avatarId] works everywhere in the app.
  // Only shown in the selection modal when isAdmin=true.
  "wathiq": require('../../assets/avatars/avatar_wathiq.png'),
};


